CREATE DATABASE ABS_FITNESS
GO

USE ABS_FITNESS
GO

CREATE TABLE users(
id INT IDENTITY (1,1) PRIMARY KEY,
username VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
age INT NOT NULL,
password VARCHAR(255) NOT NULL,
createdAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE workouts(
	id INT IDENTITY(1,1) PRIMARY KEY,
	userId INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
	workoutType VARCHAR(25) NOT NULL,
	duration INT NOT NULL,
	calories INT NOT NULL,
	notes VARCHAR(255),
	workout_date DATE NOT NULL,
	createdAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE goals(
	id INT IDENTITY(1,1) PRIMARY KEY,
	userId INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
	description VARCHAR(255) NOT NULL,
	target_date DATE NOT NULL,
	status VARCHAR(20) NOT NULL,
	createdAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE userProfiles(
	id INT IDENTITY (1,1) PRIMARY KEY,
	userId INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
	age INT NULL,
	gender VARCHAR(10) NULL,
	height_cm FLOAT NULL,
	weight_kg FLOAT NULL,
	createdAt DATETIME DEFAULT GETDATE(),
	updatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE userActivity(
	id INT IDENTITY(1,1) PRIMARY KEY,
	userId INT NOT NULL FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,

	--tokens
	token VARCHAR(255) NOT NULL,
	tokenType VARCHAR(20) NOT NULL,
	tokenExpiry DATETIME NULL,

	--activiy logs
	activityType VARCHAR(100) NULL,
	activityDescription VARCHAR(100) NULL,
	activityTimestamp DATETIME DEFAULT GETDATE(),
	ipAddress VARCHAR(60) NULL
)
